name = "Reece modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42e1d8d5afcd035f3f874dac62b2bdbcd59e3a258a802a3e26f19c0d229316e5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
