name = "Reece modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ae54826bd9ecd14360cba7f884376d38a766be3d7c37e0e6538ac586ffd2041"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
