name = "Reece modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de8e9085eaf7241a7825137ed82b92372e151bcbff032d729bf2146bff73e54a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
